name: Webapp PR workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Webapp PR Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'
      
      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql start
          echo secrets: ${{ secrets }}
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD '${{ secrets.DB_PASS }}';"
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_DBNAME }};"

      - name: Install dependencies
        run: npm install

      - name: Starting server
        run: node server.js
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_DBNAME: ${{ secrets.DB_DBNAME }}
          DB_DIALECT: "postgres"

      - name: Setting up PostgreSQL
        run: |
          echo "Setting up PostgreSQL environment variables..."
          echo "DB_USER = ${{ secrets.DB_USER }}"
          echo "DB_HOST = ${{ secrets.DB_HOST }}"
          DB_PASS: ${{ secrets.DB_PASS }}
          echo "DB_DBNAME = ${{ secrets.DB_DBNAME }}"
          echo "DB_DIALECT = postgres"
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_DBNAME: ${{ secrets.DB_DBNAME }}
          DB_DIALECT: "postgres"

      - name: Run tests
        run: npm test
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_DBNAME: ${{ secrets.DB_DBNAME }}
          DB_DIALECT: "postgres"